### ISSUE TITLE
Consider using mountable XT-60 sockets

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-valdis#24]
Maybe the use of a mountable XT-60 socket like this is good to power the robot.
![image](https://user-images.githubusercontent.com/5435954/204098097-27a336d4-4fb4-4d8c-a975-2981d5dd4e88.png)

![image](https://user-images.githubusercontent.com/5435954/204098091-9977059a-917a-46cf-ac09-a2a53e8f3762.png)

**Comment by vinku34** [comment]
do we have this kind of mountable connector or would I have to make a holder to make it mountable?

**Comment by Akustav** [comment]
They are available in the lab

**Comment by vinku34** [comment]
I made a variant with these mountable sockets. The current issue would be on the side with the NUC power cable. Right now I can move it closer to the edge a bit but im not 100% sure if it will clear the power cable or not.
![Screenshot 2022-12-05 201746](https://user-images.githubusercontent.com/74118736/205712087-503607eb-6def-4515-b9dc-4ff7fbf05f33.png)

Also the holes in the rear acted as a place to shove the battery voltage displays. I have an Idea to mount them here with 3D printed boxes and screw in from the inside with the same flush fit as most of the bolts I have. with little indents for nuts so that I dont have to thread plastic
![Screenshot 2022-12-05 201428](https://user-images.githubusercontent.com/74118736/205711439-dbc7aff9-c2d4-4cda-a396-beba54853b1f.png)

**Comment by Akustav** [comment]
Seems reasonable. Also FYI, the XT-60 sockets themselves have threaded inserts, so you just need a 3mm hole to mount them. Your current holes are 2.5mm
